# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7ZfESjh7btFC07g9udsddWlhF2WAUsC
"""

!pip install opencv-python



from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "koprik.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "salom.jpg")

cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "gullar.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = 2 * np.sin(x) + 4


plt.plot(x, y)
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Sinusoidal graph")
plt.grid()
plt.show()

x = np.random.rand(50)
y = np.random.rand(50)

plt.scatter(x, y, color='blue')
plt.title('Tasodifiy Nuqtalar Scatter Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.show()

import pandas as pd
fayl= pd.read_csv("hi.csv")
print(fayl)
db=pd.DataFrame(fayl)
print(db)

filtered_db = db[db['Country'] == 'Afghanistan']
print(len(filtered_db))

filtered_db = db[db['Continent'] == 'Asia']
print(len(filtered_db))

filtered_db = db[db['Continent'] == 'Europe']
print(len(filtered_db))